name: Build Gatsby Site

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build Gatsby Site
        uses: jzweifel/gatsby-cli-github-action@master
        with:
          gatsby-arg: build
