name: Checks on Push

on:
  push:
    branches: [main]

jobs:
  build:
    name: Automated checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code 🛎
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache Dependencies 💽
        uses: actions/cache@v2.1.4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Packages 📦
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run ESLint Checks ✅
        run: yarn lint

      - name: Run TypeScript Checks ✅
        run: yarn type-check

      - name: Build Gatsby Site ⚙️
        run: yarn build
